# Configuration centralisée pour le service Gestion Événement
# Ce fichier doit être placé dans le dossier: config-repo/

### DATABASE ###
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionEvenement?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  ### JPA / HIBERNATE ###
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
  ### MVC ###
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

### SERVER CONFIGURATION ###
server:
  servlet:
    context-path: /GestionEvenement
  port: 8082

### LOGGING CONFIGURATION ###
logging:
  level:
    com.zaxxer.hikari: INFO
    org.springframework: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{60} - %msg%n"

### SWAGGER / SPRINGDOC ###
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

### CONFIGURATION INFO ###
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always